"""Create CM3_RUN_HISTORY and CM3_RUN_TESTS tables.

This is the first Valdo migration.  The schema matches the manual Oracle DDL
at ``sql/cm3int/setup_cm3_run_history.sql`` and the column names used in
``src/database/run_history.py``.

Cross-dialect design decisions
-------------------------------
- ``run_id`` is ``String(36)`` to hold a UUID on all dialects (Oracle stores
  UUID as VARCHAR2(36); SQLite/PostgreSQL use TEXT/VARCHAR).
- ``test_id`` uses ``Integer`` with ``autoincrement=True``.  On Oracle this
  maps to a ``GENERATED BY DEFAULT AS IDENTITY`` column; on PostgreSQL it
  becomes a ``SERIAL``-backed integer; on SQLite it becomes ``INTEGER PRIMARY
  KEY AUTOINCREMENT``.
- Timestamps use ``DateTime`` (dialect-agnostic).  Oracle renders this as
  ``TIMESTAMP``; PostgreSQL as ``TIMESTAMP WITHOUT TIME ZONE``; SQLite as
  ``DATETIME``.
- ``pass_count``, ``fail_count``, ``skip_count``, ``total_count``,
  ``error_count`` use ``Integer`` (Oracle ``NUMBER(6)`` / ``NUMBER(10)``).
- ``row_count`` and ``duration_secs`` use ``Numeric`` to preserve decimal
  precision on Oracle (``NUMBER(12)`` / ``NUMBER(8,2)``).
- ``server_default=sa.text('CURRENT_TIMESTAMP')`` works on Oracle, PostgreSQL,
  and SQLite.
- Two indexes are created to match the Oracle DDL:
  ``IDX_RUN_HISTORY_TS`` on ``CM3_RUN_HISTORY.run_timestamp`` and
  ``IDX_RUN_TESTS_RUN_ID`` on ``CM3_RUN_TESTS.run_id``.

Revision ID: 0001
Revises:
Create Date: 2026-03-30
"""
from alembic import op
import sqlalchemy as sa

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create CM3_RUN_HISTORY (parent) then CM3_RUN_TESTS (child with FK)."""
    op.create_table(
        "CM3_RUN_HISTORY",
        sa.Column("run_id", sa.String(36), primary_key=True),
        sa.Column("suite_name", sa.String(200), nullable=False),
        sa.Column("environment", sa.String(100), nullable=False),
        sa.Column("run_timestamp", sa.DateTime, nullable=False),
        sa.Column("status", sa.String(20), nullable=False),
        sa.Column("pass_count", sa.Integer, nullable=False, server_default=sa.text("0")),
        sa.Column("fail_count", sa.Integer, nullable=False, server_default=sa.text("0")),
        sa.Column("skip_count", sa.Integer, nullable=False, server_default=sa.text("0")),
        sa.Column("total_count", sa.Integer, nullable=False, server_default=sa.text("0")),
        sa.Column("report_url", sa.String(500), nullable=True),
        sa.Column("archive_path", sa.String(1000), nullable=True),
        sa.Column(
            "created_ts",
            sa.DateTime,
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
    )
    op.create_index("IDX_RUN_HISTORY_TS", "CM3_RUN_HISTORY", ["run_timestamp"])

    op.create_table(
        "CM3_RUN_TESTS",
        sa.Column("test_id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column(
            "run_id",
            sa.String(36),
            sa.ForeignKey("CM3_RUN_HISTORY.run_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("test_name", sa.String(200), nullable=False),
        sa.Column("test_type", sa.String(50), nullable=False),
        sa.Column("status", sa.String(20), nullable=False),
        sa.Column("row_count", sa.Numeric(12, 0), nullable=True),
        sa.Column("error_count", sa.Integer, nullable=True, server_default=sa.text("0")),
        sa.Column("duration_secs", sa.Numeric(8, 2), nullable=True),
        sa.Column("report_path", sa.String(1000), nullable=True),
        sa.Column(
            "created_ts",
            sa.DateTime,
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
    )
    op.create_index("IDX_RUN_TESTS_RUN_ID", "CM3_RUN_TESTS", ["run_id"])


def downgrade() -> None:
    """Drop CM3_RUN_TESTS (child) then CM3_RUN_HISTORY (parent) — respects FK."""
    op.drop_index("IDX_RUN_TESTS_RUN_ID", table_name="CM3_RUN_TESTS")
    op.drop_table("CM3_RUN_TESTS")
    op.drop_index("IDX_RUN_HISTORY_TS", table_name="CM3_RUN_HISTORY")
    op.drop_table("CM3_RUN_HISTORY")
